DROP TABLE IF EXISTS RCD_V3_to_V2;
CREATE TABLE rctctv3map (
    MAPID VARCHAR(38) NOT NULL,
    V2_CONCEPTID VARCHAR(5) NOT NULL,
    V2_TERMID VARCHAR(2) NOT NULL,
    CTV3_TERMID VARCHAR(5) NOT NULL,
    CTV3_TERMTYP VARCHAR(1) NOT NULL,
    CTV3_CONCEPTID VARCHAR(5) NOT NULL,
    USE_CTV3_TERMID VARCHAR(5) NOT NULL,
    STAT VARCHAR(1) NOT NULL,
    MAPTYP VARCHAR(3) NOT NULL,
    MAPSTATUS INTEGER NOT NULL,
    EFFECTIVEDATE INTEGER NOT NULL,
    IS_ASSURED INTEGER NOT NULL
);
LOAD DATA LOCAL INFILE '<<READ DATA>>/data migration/nhs_datamigration_21.0.0_20160401000001/Mapping Tables/Updated/Clinically Assured/rctctv3map_uk_20160401000001.txt'
INTO TABLE RCD_V3_to_V2
FIELDS TERMINATED BY '\t' ENCLOSED BY '';
